// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(TaskChampionFFIFFI)
import TaskChampionFFIFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_taskchampion_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_taskchampion_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTaskchampionFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Holds the executor for a TaskChampion session.
 *
 * Construct once at startup; all task operations are async methods
 * on this object. Each method creates an ephemeral [`Replica`] — no
 * persistent state is held between calls, making concurrent use safe.
 */
public protocol FfiSessionProtocol: AnyObject, Sendable {
    
    /**
     * Return all tasks (pending, completed, deleted).
     */
    func allTasks() async throws  -> [FfiTask]
    
    /**
     * Create a new task with the given UUID and description.
     *
     * The task is immediately committed with `status: Pending` and `entry: now`.
     */
    func createTask(uuid: String, description: String) async throws  -> FfiTask
    
    /**
     * Return all dependency edges as `(from_uuid depends_on to_uuid)` pairs.
     */
    func dependencyMap() async throws  -> [FfiDependencyEdge]
    
    /**
     * Get the color associated with a tag name.
     *
     * Returns `None` if no color has been set for this tag.
     */
    func getTagColor(name: String) async throws  -> String?
    
    /**
     * Fetch a single task by UUID. Returns `None` if not found.
     */
    func getTask(uuid: String) async throws  -> FfiTask?
    
    /**
     * Return pending tasks only.
     */
    func pendingTasks() async throws  -> [FfiTask]
    
    /**
     * Set the color for a tag name.
     *
     * If a color already exists for this tag, it is updated.
     */
    func setTagColor(name: String, color: String) async throws 
    
    /**
     * Return the task tree as a flat list of [`FfiTreeNode`]s.
     */
    func treeMap() async throws  -> [FfiTreeNode]
    
    /**
     * Atomically undo the last operation group.
     *
     * Returns `true` if an undo was performed, `false` if there is nothing to undo.
     */
    func undo() async throws  -> Bool
    
    /**
     * Apply a batch of mutations to a task in a single transaction.
     *
     * All mutations share one undo point — a single `undo()` call will reverse
     * the entire batch.
     *
     * Returns the updated task, or `None` if the task no longer exists after the
     * mutations (defensive; should not happen via normal mutations).
     */
    func mutateTask(uuid: String, mutations: [TaskMutation]) async throws  -> FfiTask?
    
}
/**
 * Holds the executor for a TaskChampion session.
 *
 * Construct once at startup; all task operations are async methods
 * on this object. Each method creates an ephemeral [`Replica`] — no
 * persistent state is held between calls, making concurrent use safe.
 */
open class FfiSession: FfiSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_taskchampion_ffi_fn_clone_ffisession(self.handle, $0) }
    }
    /**
     * Create a new session.
     */
public convenience init(executor: FfiSqlExecutor) {
    let handle =
        try! rustCall() {
    uniffi_taskchampion_ffi_fn_constructor_ffisession_new(
        FfiConverterTypeFfiSqlExecutor_lower(executor),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_taskchampion_ffi_fn_free_ffisession(handle, $0) }
    }

    

    
    /**
     * Return all tasks (pending, completed, deleted).
     */
open func allTasks()async throws  -> [FfiTask]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_all_tasks(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiTask.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Create a new task with the given UUID and description.
     *
     * The task is immediately committed with `status: Pending` and `entry: now`.
     */
open func createTask(uuid: String, description: String)async throws  -> FfiTask  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_create_task(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(uuid),FfiConverterString.lower(description)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiTask_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return all dependency edges as `(from_uuid depends_on to_uuid)` pairs.
     */
open func dependencyMap()async throws  -> [FfiDependencyEdge]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_dependency_map(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiDependencyEdge.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Get the color associated with a tag name.
     *
     * Returns `None` if no color has been set for this tag.
     */
open func getTagColor(name: String)async throws  -> String?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_get_tag_color(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(name)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Fetch a single task by UUID. Returns `None` if not found.
     */
open func getTask(uuid: String)async throws  -> FfiTask?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_get_task(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(uuid)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeFfiTask.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return pending tasks only.
     */
open func pendingTasks()async throws  -> [FfiTask]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_pending_tasks(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiTask.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Set the color for a tag name.
     *
     * If a color already exists for this tag, it is updated.
     */
open func setTagColor(name: String, color: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_set_tag_color(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(name),FfiConverterString.lower(color)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_void,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_void,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return the task tree as a flat list of [`FfiTreeNode`]s.
     */
open func treeMap()async throws  -> [FfiTreeNode]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_tree_map(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiTreeNode.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Atomically undo the last operation group.
     *
     * Returns `true` if an undo was performed, `false` if there is nothing to undo.
     */
open func undo()async throws  -> Bool  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_undo(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_i8,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_i8,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Apply a batch of mutations to a task in a single transaction.
     *
     * All mutations share one undo point — a single `undo()` call will reverse
     * the entire batch.
     *
     * Returns the updated task, or `None` if the task no longer exists after the
     * mutations (defensive; should not happen via normal mutations).
     */
open func mutateTask(uuid: String, mutations: [TaskMutation])async throws  -> FfiTask?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisession_mutate_task(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(uuid),FfiConverterSequenceTypeTaskMutation.lower(mutations)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeFfiTask.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiSession

    public static func lift(_ handle: UInt64) throws -> FfiSession {
        return FfiSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSession_lift(_ handle: UInt64) throws -> FfiSession {
    return try FfiConverterTypeFfiSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSession_lower(_ value: FfiSession) -> UInt64 {
    return FfiConverterTypeFfiSession.lower(value)
}






/**
 * Callback interface for host-side SQL execution.
 *
 * The host (Swift/Kotlin) implements this trait with native async/await.
 * TaskChampion calls these methods to read/write task data through the
 * host's database connection.
 */
public protocol FfiSqlExecutor: AnyObject, Sendable {
    
    /**
     * Execute a read query returning at most one row as a JSON object string.
     * Returns `None` if no rows match.
     */
    func queryOne(sql: String, params: [FfiSqlParam]) async throws  -> String?
    
    /**
     * Execute a read query returning all matching rows as JSON object strings.
     */
    func queryAll(sql: String, params: [FfiSqlParam]) async throws  -> [String]
    
    /**
     * Execute a batch of write statements atomically.
     * The host MUST wrap these in a transaction.
     */
    func executeBatch(statements: [FfiSqlStatement]) async throws 
    
}
/**
 * Callback interface for host-side SQL execution.
 *
 * The host (Swift/Kotlin) implements this trait with native async/await.
 * TaskChampion calls these methods to read/write task data through the
 * host's database connection.
 */
open class FfiSqlExecutorImpl: FfiSqlExecutor, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_taskchampion_ffi_fn_clone_ffisqlexecutor(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_taskchampion_ffi_fn_free_ffisqlexecutor(handle, $0) }
    }

    

    
    /**
     * Execute a read query returning at most one row as a JSON object string.
     * Returns `None` if no rows match.
     */
open func queryOne(sql: String, params: [FfiSqlParam])async throws  -> String?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisqlexecutor_query_one(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(sql),FfiConverterSequenceTypeFfiSqlParam.lower(params)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionString.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Execute a read query returning all matching rows as JSON object strings.
     */
open func queryAll(sql: String, params: [FfiSqlParam])async throws  -> [String]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisqlexecutor_query_all(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(sql),FfiConverterSequenceTypeFfiSqlParam.lower(params)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Execute a batch of write statements atomically.
     * The host MUST wrap these in a transaction.
     */
open func executeBatch(statements: [FfiSqlStatement])async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_taskchampion_ffi_fn_method_ffisqlexecutor_execute_batch(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceTypeFfiSqlStatement.lower(statements)
                )
            },
            pollFunc: ffi_taskchampion_ffi_rust_future_poll_void,
            completeFunc: ffi_taskchampion_ffi_rust_future_complete_void,
            freeFunc: ffi_taskchampion_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceFfiSqlExecutor {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceFfiSqlExecutor] = [UniffiVTableCallbackInterfaceFfiSqlExecutor(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeFfiSqlExecutor.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface FfiSqlExecutor: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeFfiSqlExecutor.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface FfiSqlExecutor: handle missing in uniffiClone")
            }
        },
        queryOne: { (
            uniffiHandle: UInt64,
            sql: RustBuffer,
            params: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> String? in
                guard let uniffiObj = try? FfiConverterTypeFfiSqlExecutor.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.queryOne(
                     sql: try FfiConverterString.lift(sql),
                     params: try FfiConverterSequenceTypeFfiSqlParam.lift(params)
                )
            }

            let uniffiHandleSuccess = { (returnValue: String?) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: FfiConverterOptionString.lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeFfiError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        },
        queryAll: { (
            uniffiHandle: UInt64,
            sql: RustBuffer,
            params: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteRustBuffer,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> [String] in
                guard let uniffiObj = try? FfiConverterTypeFfiSqlExecutor.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.queryAll(
                     sql: try FfiConverterString.lift(sql),
                     params: try FfiConverterSequenceTypeFfiSqlParam.lift(params)
                )
            }

            let uniffiHandleSuccess = { (returnValue: [String]) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: FfiConverterSequenceString.lower(returnValue),
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultRustBuffer(
                        returnValue: RustBuffer.empty(),
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeFfiError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        },
        executeBatch: { (
            uniffiHandle: UInt64,
            statements: RustBuffer,
            uniffiFutureCallback: @escaping UniffiForeignFutureCompleteVoid,
            uniffiCallbackData: UInt64,
            uniffiOutDroppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
        ) in
            let makeCall = {
                () async throws -> () in
                guard let uniffiObj = try? FfiConverterTypeFfiSqlExecutor.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try await uniffiObj.executeBatch(
                     statements: try FfiConverterSequenceTypeFfiSqlStatement.lift(statements)
                )
            }

            let uniffiHandleSuccess = { (returnValue: ()) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultVoid(
                        callStatus: RustCallStatus()
                    )
                )
            }
            let uniffiHandleError = { (statusCode, errorBuf) in
                uniffiFutureCallback(
                    uniffiCallbackData,
                    UniffiForeignFutureResultVoid(
                        callStatus: RustCallStatus(code: statusCode, errorBuf: errorBuf)
                    )
                )
            }
            uniffiTraitInterfaceCallAsyncWithError(
                makeCall: makeCall,
                handleSuccess: uniffiHandleSuccess,
                handleError: uniffiHandleError,
                lowerError: FfiConverterTypeFfiError_lower,
                droppedCallback: uniffiOutDroppedCallback
            )
        }
    )]
}

private func uniffiCallbackInitFfiSqlExecutor() {
    uniffi_taskchampion_ffi_fn_init_callback_vtable_ffisqlexecutor(UniffiCallbackInterfaceFfiSqlExecutor.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSqlExecutor: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<FfiSqlExecutor>()

    typealias FfiType = UInt64
    typealias SwiftType = FfiSqlExecutor

    public static func lift(_ handle: UInt64) throws -> FfiSqlExecutor {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return FfiSqlExecutorImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: FfiSqlExecutor) -> UInt64 {
         if let rustImpl = value as? FfiSqlExecutorImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSqlExecutor {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSqlExecutor, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlExecutor_lift(_ handle: UInt64) throws -> FfiSqlExecutor {
    return try FfiConverterTypeFfiSqlExecutor.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlExecutor_lower(_ value: FfiSqlExecutor) -> UInt64 {
    return FfiConverterTypeFfiSqlExecutor.lower(value)
}




/**
 * A single task annotation.
 */
public struct FfiAnnotation: Equatable, Hashable {
    /**
     * Unix epoch seconds.
     */
    public var entry: Int64
    public var description: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Unix epoch seconds.
         */entry: Int64, description: String) {
        self.entry = entry
        self.description = description
    }

    

    
}

#if compiler(>=6)
extension FfiAnnotation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAnnotation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAnnotation {
        return
            try FfiAnnotation(
                entry: FfiConverterInt64.read(from: &buf), 
                description: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAnnotation, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.entry, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnnotation_lift(_ buf: RustBuffer) throws -> FfiAnnotation {
    return try FfiConverterTypeFfiAnnotation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnnotation_lower(_ value: FfiAnnotation) -> RustBuffer {
    return FfiConverterTypeFfiAnnotation.lower(value)
}


/**
 * A dependency edge: `from_uuid` depends on `to_uuid`.
 */
public struct FfiDependencyEdge: Equatable, Hashable {
    /**
     * The task that has the dependency.
     */
    public var fromUuid: String
    /**
     * The task being depended upon.
     */
    public var toUuid: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The task that has the dependency.
         */fromUuid: String, 
        /**
         * The task being depended upon.
         */toUuid: String) {
        self.fromUuid = fromUuid
        self.toUuid = toUuid
    }

    

    
}

#if compiler(>=6)
extension FfiDependencyEdge: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDependencyEdge: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDependencyEdge {
        return
            try FfiDependencyEdge(
                fromUuid: FfiConverterString.read(from: &buf), 
                toUuid: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDependencyEdge, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fromUuid, into: &buf)
        FfiConverterString.write(value.toUuid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDependencyEdge_lift(_ buf: RustBuffer) throws -> FfiDependencyEdge {
    return try FfiConverterTypeFfiDependencyEdge.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDependencyEdge_lower(_ value: FfiDependencyEdge) -> RustBuffer {
    return FfiConverterTypeFfiDependencyEdge.lower(value)
}


/**
 * A single SQL statement with parameters, for batched execution.
 */
public struct FfiSqlStatement: Equatable, Hashable {
    public var sql: String
    public var params: [FfiSqlParam]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sql: String, params: [FfiSqlParam]) {
        self.sql = sql
        self.params = params
    }

    

    
}

#if compiler(>=6)
extension FfiSqlStatement: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSqlStatement: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSqlStatement {
        return
            try FfiSqlStatement(
                sql: FfiConverterString.read(from: &buf), 
                params: FfiConverterSequenceTypeFfiSqlParam.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSqlStatement, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sql, into: &buf)
        FfiConverterSequenceTypeFfiSqlParam.write(value.params, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlStatement_lift(_ buf: RustBuffer) throws -> FfiSqlStatement {
    return try FfiConverterTypeFfiSqlStatement.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlStatement_lower(_ value: FfiSqlStatement) -> RustBuffer {
    return FfiConverterTypeFfiSqlStatement.lower(value)
}


/**
 * Flat representation of a task suitable for FFI transfer.
 */
public struct FfiTask: Equatable, Hashable {
    public var uuid: String
    public var status: FfiStatus
    public var description: String
    public var priority: String
    /**
     * Unix epoch seconds, or `None` if not set.
     */
    public var entry: Int64?
    public var modified: Int64?
    public var due: Int64?
    public var wait: Int64?
    /**
     * Parent task UUID as a string, or `None`.
     */
    public var parent: String?
    public var position: String?
    /**
     * User-visible tags (synthetic tags excluded).
     */
    public var tags: [String]
    public var annotations: [FfiAnnotation]
    /**
     * UUIDs of tasks this task depends on.
     */
    public var dependencies: [String]
    public var isWaiting: Bool
    public var isActive: Bool
    public var isBlocked: Bool
    public var isBlocking: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, status: FfiStatus, description: String, priority: String, 
        /**
         * Unix epoch seconds, or `None` if not set.
         */entry: Int64?, modified: Int64?, due: Int64?, wait: Int64?, 
        /**
         * Parent task UUID as a string, or `None`.
         */parent: String?, position: String?, 
        /**
         * User-visible tags (synthetic tags excluded).
         */tags: [String], annotations: [FfiAnnotation], 
        /**
         * UUIDs of tasks this task depends on.
         */dependencies: [String], isWaiting: Bool, isActive: Bool, isBlocked: Bool, isBlocking: Bool) {
        self.uuid = uuid
        self.status = status
        self.description = description
        self.priority = priority
        self.entry = entry
        self.modified = modified
        self.due = due
        self.wait = wait
        self.parent = parent
        self.position = position
        self.tags = tags
        self.annotations = annotations
        self.dependencies = dependencies
        self.isWaiting = isWaiting
        self.isActive = isActive
        self.isBlocked = isBlocked
        self.isBlocking = isBlocking
    }

    

    
}

#if compiler(>=6)
extension FfiTask: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTask: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTask {
        return
            try FfiTask(
                uuid: FfiConverterString.read(from: &buf), 
                status: FfiConverterTypeFfiStatus.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                priority: FfiConverterString.read(from: &buf), 
                entry: FfiConverterOptionInt64.read(from: &buf), 
                modified: FfiConverterOptionInt64.read(from: &buf), 
                due: FfiConverterOptionInt64.read(from: &buf), 
                wait: FfiConverterOptionInt64.read(from: &buf), 
                parent: FfiConverterOptionString.read(from: &buf), 
                position: FfiConverterOptionString.read(from: &buf), 
                tags: FfiConverterSequenceString.read(from: &buf), 
                annotations: FfiConverterSequenceTypeFfiAnnotation.read(from: &buf), 
                dependencies: FfiConverterSequenceString.read(from: &buf), 
                isWaiting: FfiConverterBool.read(from: &buf), 
                isActive: FfiConverterBool.read(from: &buf), 
                isBlocked: FfiConverterBool.read(from: &buf), 
                isBlocking: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTask, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterTypeFfiStatus.write(value.status, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.priority, into: &buf)
        FfiConverterOptionInt64.write(value.entry, into: &buf)
        FfiConverterOptionInt64.write(value.modified, into: &buf)
        FfiConverterOptionInt64.write(value.due, into: &buf)
        FfiConverterOptionInt64.write(value.wait, into: &buf)
        FfiConverterOptionString.write(value.parent, into: &buf)
        FfiConverterOptionString.write(value.position, into: &buf)
        FfiConverterSequenceString.write(value.tags, into: &buf)
        FfiConverterSequenceTypeFfiAnnotation.write(value.annotations, into: &buf)
        FfiConverterSequenceString.write(value.dependencies, into: &buf)
        FfiConverterBool.write(value.isWaiting, into: &buf)
        FfiConverterBool.write(value.isActive, into: &buf)
        FfiConverterBool.write(value.isBlocked, into: &buf)
        FfiConverterBool.write(value.isBlocking, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTask_lift(_ buf: RustBuffer) throws -> FfiTask {
    return try FfiConverterTypeFfiTask.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTask_lower(_ value: FfiTask) -> RustBuffer {
    return FfiConverterTypeFfiTask.lower(value)
}


/**
 * A node in the task tree (parent/child hierarchy).
 */
public struct FfiTreeNode: Equatable, Hashable {
    public var uuid: String
    /**
     * Direct child UUIDs.
     */
    public var children: [String]
    public var parent: String?
    /**
     * Always `None` when returned from `tree_map()` — position lives on the
     * `Task`, not on the `TreeMap`. Cross-reference with `all_tasks()` to
     * obtain per-node position values.
     */
    public var position: String?
    /**
     * `true` if the node has at least one pending child.
     */
    public var isPending: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, 
        /**
         * Direct child UUIDs.
         */children: [String], parent: String?, 
        /**
         * Always `None` when returned from `tree_map()` — position lives on the
         * `Task`, not on the `TreeMap`. Cross-reference with `all_tasks()` to
         * obtain per-node position values.
         */position: String?, 
        /**
         * `true` if the node has at least one pending child.
         */isPending: Bool) {
        self.uuid = uuid
        self.children = children
        self.parent = parent
        self.position = position
        self.isPending = isPending
    }

    

    
}

#if compiler(>=6)
extension FfiTreeNode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiTreeNode: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiTreeNode {
        return
            try FfiTreeNode(
                uuid: FfiConverterString.read(from: &buf), 
                children: FfiConverterSequenceString.read(from: &buf), 
                parent: FfiConverterOptionString.read(from: &buf), 
                position: FfiConverterOptionString.read(from: &buf), 
                isPending: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiTreeNode, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterSequenceString.write(value.children, into: &buf)
        FfiConverterOptionString.write(value.parent, into: &buf)
        FfiConverterOptionString.write(value.position, into: &buf)
        FfiConverterBool.write(value.isPending, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTreeNode_lift(_ buf: RustBuffer) throws -> FfiTreeNode {
    return try FfiConverterTypeFfiTreeNode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiTreeNode_lower(_ value: FfiTreeNode) -> RustBuffer {
    return FfiConverterTypeFfiTreeNode.lower(value)
}


/**
 * Error type returned by all FFI functions.
 *
 * Variants are designed for programmatic matching on the Swift/Kotlin side.
 * Each carries enough context for the host to decide on UX (retry, show
 * message, refresh cache, etc.) without parsing strings.
 */
public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The referenced task does not exist.
     */
    case TaskNotFound(uuid: String
    )
    /**
     * A task with this UUID already exists (create collision).
     */
    case TaskAlreadyExists(uuid: String
    )
    /**
     * Caller-side validation error (bad UUID format, invalid tag, etc.).
     */
    case InvalidInput(message: String
    )
    /**
     * Storage-layer error (SQL execution failure, connection issue).
     */
    case Storage(message: String
    )
    /**
     * Unexpected internal error (bug, catch-all).
     */
    case Internal(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .TaskNotFound(
            uuid: try FfiConverterString.read(from: &buf)
            )
        case 2: return .TaskAlreadyExists(
            uuid: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .TaskNotFound(uuid):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .TaskAlreadyExists(uuid):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .InvalidInput(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Storage(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * SQL parameter for external storage queries.
 */

public enum FfiSqlParam: Equatable, Hashable {
    
    case text(value: String
    )
    case null





}

#if compiler(>=6)
extension FfiSqlParam: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSqlParam: FfiConverterRustBuffer {
    typealias SwiftType = FfiSqlParam

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSqlParam {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(value: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .null
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSqlParam, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        
        case .null:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlParam_lift(_ buf: RustBuffer) throws -> FfiSqlParam {
    return try FfiConverterTypeFfiSqlParam.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSqlParam_lower(_ value: FfiSqlParam) -> RustBuffer {
    return FfiConverterTypeFfiSqlParam.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Task status, mirroring `taskchampion::Status`.
 */

public enum FfiStatus: Equatable, Hashable {
    
    case pending
    case completed
    case deleted
    case recurring
    case unknown(value: String
    )





}

#if compiler(>=6)
extension FfiStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStatus: FfiConverterRustBuffer {
    typealias SwiftType = FfiStatus

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStatus {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pending
        
        case 2: return .completed
        
        case 3: return .deleted
        
        case 4: return .recurring
        
        case 5: return .unknown(value: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiStatus, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pending:
            writeInt(&buf, Int32(1))
        
        
        case .completed:
            writeInt(&buf, Int32(2))
        
        
        case .deleted:
            writeInt(&buf, Int32(3))
        
        
        case .recurring:
            writeInt(&buf, Int32(4))
        
        
        case let .unknown(value):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(value, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStatus_lift(_ buf: RustBuffer) throws -> FfiStatus {
    return try FfiConverterTypeFfiStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStatus_lower(_ value: FfiStatus) -> RustBuffer {
    return FfiConverterTypeFfiStatus.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Enum of all supported task mutations.
 *
 * Pass a `Vec<TaskMutation>` to `mutate_task` — all mutations are applied in
 * a single transaction with one undo point.
 */

public enum TaskMutation: Equatable, Hashable {
    
    case setDescription(value: String
    )
    case setStatus(status: FfiStatus
    )
    case setPriority(value: String
    )
    /**
     * `None` clears the field.
     */
    case setDue(epoch: Int64?
    )
    case setWait(epoch: Int64?
    )
    case setEntry(epoch: Int64?
    )
    case setParent(uuid: String?
    )
    case setPosition(value: String?
    )
    case addTag(tag: String
    )
    case removeTag(tag: String
    )
    case addAnnotation(entry: Int64, description: String
    )
    case removeAnnotation(entry: Int64
    )
    case addDependency(uuid: String
    )
    case removeDependency(uuid: String
    )
    /**
     * Mark the task as completed.
     */
    case done
    /**
     * Start tracking active time.
     */
    case start
    /**
     * Stop tracking active time.
     */
    case stop
    /**
     * Soft-delete: sets status to `Deleted`.
     */
    case delete





}

#if compiler(>=6)
extension TaskMutation: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTaskMutation: FfiConverterRustBuffer {
    typealias SwiftType = TaskMutation

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TaskMutation {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .setDescription(value: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .setStatus(status: try FfiConverterTypeFfiStatus.read(from: &buf)
        )
        
        case 3: return .setPriority(value: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .setDue(epoch: try FfiConverterOptionInt64.read(from: &buf)
        )
        
        case 5: return .setWait(epoch: try FfiConverterOptionInt64.read(from: &buf)
        )
        
        case 6: return .setEntry(epoch: try FfiConverterOptionInt64.read(from: &buf)
        )
        
        case 7: return .setParent(uuid: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 8: return .setPosition(value: try FfiConverterOptionString.read(from: &buf)
        )
        
        case 9: return .addTag(tag: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .removeTag(tag: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .addAnnotation(entry: try FfiConverterInt64.read(from: &buf), description: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .removeAnnotation(entry: try FfiConverterInt64.read(from: &buf)
        )
        
        case 13: return .addDependency(uuid: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .removeDependency(uuid: try FfiConverterString.read(from: &buf)
        )
        
        case 15: return .done
        
        case 16: return .start
        
        case 17: return .stop
        
        case 18: return .delete
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TaskMutation, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .setDescription(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        
        case let .setStatus(status):
            writeInt(&buf, Int32(2))
            FfiConverterTypeFfiStatus.write(status, into: &buf)
            
        
        case let .setPriority(value):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(value, into: &buf)
            
        
        case let .setDue(epoch):
            writeInt(&buf, Int32(4))
            FfiConverterOptionInt64.write(epoch, into: &buf)
            
        
        case let .setWait(epoch):
            writeInt(&buf, Int32(5))
            FfiConverterOptionInt64.write(epoch, into: &buf)
            
        
        case let .setEntry(epoch):
            writeInt(&buf, Int32(6))
            FfiConverterOptionInt64.write(epoch, into: &buf)
            
        
        case let .setParent(uuid):
            writeInt(&buf, Int32(7))
            FfiConverterOptionString.write(uuid, into: &buf)
            
        
        case let .setPosition(value):
            writeInt(&buf, Int32(8))
            FfiConverterOptionString.write(value, into: &buf)
            
        
        case let .addTag(tag):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(tag, into: &buf)
            
        
        case let .removeTag(tag):
            writeInt(&buf, Int32(10))
            FfiConverterString.write(tag, into: &buf)
            
        
        case let .addAnnotation(entry,description):
            writeInt(&buf, Int32(11))
            FfiConverterInt64.write(entry, into: &buf)
            FfiConverterString.write(description, into: &buf)
            
        
        case let .removeAnnotation(entry):
            writeInt(&buf, Int32(12))
            FfiConverterInt64.write(entry, into: &buf)
            
        
        case let .addDependency(uuid):
            writeInt(&buf, Int32(13))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case let .removeDependency(uuid):
            writeInt(&buf, Int32(14))
            FfiConverterString.write(uuid, into: &buf)
            
        
        case .done:
            writeInt(&buf, Int32(15))
        
        
        case .start:
            writeInt(&buf, Int32(16))
        
        
        case .stop:
            writeInt(&buf, Int32(17))
        
        
        case .delete:
            writeInt(&buf, Int32(18))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskMutation_lift(_ buf: RustBuffer) throws -> TaskMutation {
    return try FfiConverterTypeTaskMutation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTaskMutation_lower(_ value: TaskMutation) -> RustBuffer {
    return FfiConverterTypeTaskMutation.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionInt64: FfiConverterRustBuffer {
    typealias SwiftType = Int64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiTask: FfiConverterRustBuffer {
    typealias SwiftType = FfiTask?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiTask.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiTask.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiAnnotation: FfiConverterRustBuffer {
    typealias SwiftType = [FfiAnnotation]

    public static func write(_ value: [FfiAnnotation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiAnnotation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiAnnotation] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiAnnotation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiAnnotation.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiDependencyEdge: FfiConverterRustBuffer {
    typealias SwiftType = [FfiDependencyEdge]

    public static func write(_ value: [FfiDependencyEdge], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiDependencyEdge.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiDependencyEdge] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiDependencyEdge]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiDependencyEdge.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSqlStatement: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSqlStatement]

    public static func write(_ value: [FfiSqlStatement], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSqlStatement.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSqlStatement] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSqlStatement]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSqlStatement.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiTask: FfiConverterRustBuffer {
    typealias SwiftType = [FfiTask]

    public static func write(_ value: [FfiTask], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiTask.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiTask] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiTask]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiTask.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiTreeNode: FfiConverterRustBuffer {
    typealias SwiftType = [FfiTreeNode]

    public static func write(_ value: [FfiTreeNode], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiTreeNode.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiTreeNode] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiTreeNode]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiTreeNode.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSqlParam: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSqlParam]

    public static func write(_ value: [FfiSqlParam], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSqlParam.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSqlParam] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSqlParam]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSqlParam.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTaskMutation: FfiConverterRustBuffer {
    typealias SwiftType = [TaskMutation]

    public static func write(_ value: [TaskMutation], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTaskMutation.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TaskMutation] {
        let len: Int32 = try readInt(&buf)
        var seq = [TaskMutation]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTaskMutation.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureTaskchampionFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
private func uniffiTraitInterfaceCallAsync<T>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // Note: it's important we call either `handleSuccess` or `handleError` exactly once.  Each
        // call consumes an Arc reference, which means there should be no possibility of a double
        // call.  The following code is structured so that will will never call both `handleSuccess`
        // and `handleError`, even in the face of weird errors.
        //
        // On platforms that need extra machinery to make C-ABI calls, like JNA or ctypes, it's
        // possible that we fail to make either call.  However, it doesn't seem like this is
        // possible on Swift since swift can just make the C call directly.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

private func uniffiTraitInterfaceCallAsyncWithError<T, E>(
    makeCall: @escaping () async throws -> T,
    handleSuccess: @escaping (T) -> (),
    handleError: @escaping (Int8, RustBuffer) -> (),
    lowerError: @escaping (E) -> RustBuffer,
    droppedCallback: UnsafeMutablePointer<UniffiForeignFutureDroppedCallbackStruct>
) {
    let task = Task {
        // See the note in uniffiTraitInterfaceCallAsync for details on `handleSuccess` and
        // `handleError`.
        var callResult: T
        do {
            callResult = try await makeCall()
        } catch let error as E {
            handleError(CALL_ERROR, lowerError(error))
            return
        } catch {
            handleError(CALL_UNEXPECTED_ERROR, FfiConverterString.lower(String(describing: error)))
            return
        }
        handleSuccess(callResult)
    }
    let handle = UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.insert(obj: task)
    droppedCallback.pointee = UniffiForeignFutureDroppedCallbackStruct(
        handle: handle,
        free: uniffiForeignFutureDroppedCallback
    )
}

// Borrow the callback handle map implementation to store foreign future handles
// TODO: consolidate the handle-map code (https://github.com/mozilla/uniffi-rs/pull/1823)
fileprivate let UNIFFI_FOREIGN_FUTURE_HANDLE_MAP = UniffiHandleMap<UniffiForeignFutureTask>()

// Protocol for tasks that handle foreign futures.
//
// Defining a protocol allows all tasks to be stored in the same handle map.  This can't be done
// with the task object itself, since has generic parameters.
fileprivate protocol UniffiForeignFutureTask {
    func cancel()
}

extension Task: UniffiForeignFutureTask {}

private func uniffiForeignFutureDroppedCallback(handle: UInt64) {
    do {
        let task = try UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.remove(handle: handle)
        // Set the cancellation flag on the task.  If it's still running, the code can check the
        // cancellation flag or call `Task.checkCancellation()`.  If the task has completed, this is
        // a no-op.
        task.cancel()
    } catch {
        print("uniffiForeignFutureDroppedCallback: handle missing from handlemap")
    }
}

// For testing
public func uniffiForeignFutureHandleCountTaskchampionFfi() -> Int {
    UNIFFI_FOREIGN_FUTURE_HANDLE_MAP.count
}
/**
 * SQL that covers all task-related tables.
 *
 * Pass this to `db.watch()` so PowerSync re-runs your query whenever any
 * task, tag, annotation, or project row changes.
 */
public func allTaskTablesSql() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_taskchampion_ffi_fn_func_alltasktablessql($0
    )
})
}
/**
 * SQL that covers the tag colors table.
 *
 * Pass this to `db.watch()` so PowerSync re-runs your query whenever a
 * `tc_tag_colors` row changes (e.g. color set on another device via sync).
 */
public func tagColorTablesSql() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_taskchampion_ffi_fn_func_tagcolortablessql($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_taskchampion_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_func_alltasktablessql() != 52128) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_func_tagcolortablessql() != 36535) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_all_tasks() != 57965) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_create_task() != 18352) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_dependency_map() != 18621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_get_tag_color() != 63735) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_get_task() != 45469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_pending_tasks() != 10449) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_set_tag_color() != 50403) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_tree_map() != 45281) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_undo() != 18653) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisession_mutate_task() != 59757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisqlexecutor_query_one() != 60448) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisqlexecutor_query_all() != 58880) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_method_ffisqlexecutor_execute_batch() != 6036) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_taskchampion_ffi_checksum_constructor_ffisession_new() != 13705) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitFfiSqlExecutor()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTaskchampionFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all